name: Run Selenium Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver matching Chrome major version
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f1)
          echo "Detected Chrome version: $CHROME_VERSION (Major: $CHROME_MAJOR)"

          curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json" -o versions.json

          DRIVER_URL=$(jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url' versions.json)

          if [ -z "$DRIVER_URL" ]; then
            echo "❌ Could not find a matching ChromeDriver"
            exit 1
          fi

          echo "✅ Downloading ChromeDriver from $DRIVER_URL"
          curl -Lo chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium Tests
        run: mvn test

      - name: Upload test reports if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Notify Slack of build result
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
